apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: c9-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: c9-api
    spec:
      containers:
      - name: c9-api
        image: c9registry.azurecr.io/c9-api:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: c9-api-service
spec:
  selector:
    app: c9-api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30001
  type: LoadBalancer
